CLASS zbp_i_po_rap_h DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_po_rap_h.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS zbp_i_po_rap_h IMPLEMENTATION.

ENDCLASS.